NEW ADDING?

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -3,27 +3,33 @@ name: Actions with Bors
 on:
   push:
 
-##
 jobs:
-  main_job:
+  download:
     name: Main Job
     runs-on: ubuntu-latest
     steps:
-      - run: echo "Running slow tests..." && sleep 5
-
-  checks:
-    runs-on: ubuntu-latest
-    needs: main_job
-    steps:
-      - name: Install SSH key
-        uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.SSH }}
-          known_hosts: ${{ secrets.KNOWN_HOSTS }}
-
-  checks2:
-    name: check2
-    runs-on: ubuntu-latest
-    needs: main_job
-    steps:
-      - run: echo "Running slow tests..." && sleep 10
+      - name: test
+        run: |
+          exit 1                         # let's say 1st failed. for you, here could be mvn deploy command.
+      - name: retry
+        continue-on-error: true
+        if: steps.test.outcome=='failure'         # check the step outcome, retry 1st time
+        run: |
+          exit 1                                
+      - name: retry 2
+        continue-on-error: true
+        id: retry2
+        if: steps.retry1.outcome=='failure'   # check the step outcome, retry 2nd time
+        run: |
+          echo retry 2nd time
+          exit 1     
+      - name: retry 3
+        continue-on-error: true
+        id: retry3
+        if: steps.retry2.outcome=='failure'      # check the step outcome, retry 3rd time
+        run: |
+          echo retry 3rd time                
+      - name: set the status              # set the workflow status if command failed
+        run: |
+          echo fine
+          
