ch2

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -20,7 +20,7 @@ jobs:
               - 'testFolder/**'
             test2:
               - 'testFolder2/**'
-  
+    #TEST 1
   cargo-format:
     name: cargo-format
     needs: changes
@@ -28,35 +28,57 @@ jobs:
     runs-on: ubuntu-20.04
     timeout-minutes: 5
     steps:
-      - run: exit 1
-
-  cargo-format2:
-    name: cargo-format2
+      - run: exit 0
+  cargo-test:
+    name: cargo-test
     needs: changes
-    if: ${{ needs.changes.outputs.test2 }}
+    if: ${{ needs.changes.outputs.test }}
     runs-on: ubuntu-20.04
     timeout-minutes: 5
     steps:
-      - run: exit 1
+      - run: exit 0
+  cargo-ok:
+    name: cargo-ok
+    needs: 
+      - cargo-format
+      - cargo-test
+    if: ${{ needs.changes.outputs.test }}
+    runs-on: ubuntu-20.04
+    timeout-minutes: 5
+    steps:
+      - run: exit 0
 
-  cargo:
-    needs: [changes, cargo-format, cargo-format2]
-    if: ${{always()}}
-    runs-on: ubuntu-20.04
-    timeout-minutes: 5
-    steps:
-      - name: Both of them
-        if: ${{ needs.changes.outputs.test  }} || ${{ needs.changes.outputs.test2 }}
-        run: |
-          if ( ${{ needs.changes.outputs.test }} && ${{ needs.changes.outputs.test2 }} && ${{ needs.cargo-format.result == 'success'}} && ${{ needs.cargo-format2.result == 'success'}} )
-          then
-            exit 0
-          elif ( ${{ needs.changes.outputs.test }} && ${{ needs.cargo-format.result == 'success'}} && ${{ !needs.changes.outputs.test2 }} )
-          then
-            exit 0
-          elif ( ${{ needs.changes.outputs.test2 }} && ${{ needs.cargo-format2.result == 'success'}} && ${{ !needs.changes.outputs.test }} )
-          then
-            exit 0
-          else
-            exit 1
-          fi
+  #   #TEST2
+  # cargo-format2:
+  #   name: cargo-format2
+  #   needs: changes
+  #   if: ${{ needs.changes.outputs.test2 }}
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 5
+  #   steps:
+  #     - run: exit 0
+  # cargo-test2:
+  #   name: cargo-test2
+  #   needs: [changes, cargo-test]
+  #   if: ${{ always }}
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 5
+  #   steps:
+  #     - name: Rust result
+  #       run: |
+  #         if( needs.cargo-test.result == 'failure' )
+  #         then
+  #           exit 1
+  #     - run: exit 0
+  # cargo-ok2:
+  #   name: cargo-ok2
+  #   needs: 
+  #     - cargo-format2
+  #     - cargo-test2
+  #   if: ${{ needs.changes.outputs.test2 }}
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 5
+  #   steps:
+  #     - run: exit 0
+
+      
